---
title: "Demographics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages <-  c("tidyverse",
               "reshape2",
               "nlme", "lme4",
               "data.table", "psych",
               "parallel","lubridate",
              "ggpubr", "broom", "table1", "apaTables", "psych")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```

Set Up
```{r}
gorilla_data <- read.csv("/Volumes/devbrainlab/IndividualDifferencesMentalizing/IDMT_Data_Complete.csv")
prolific_data <- read.csv("/Volumes/devbrainlab/IndividualDifferencesMentalizing/NATE_PROLIFIC_COMPLETE.csv")

```

Demographics Table
```{r}
prolific_data <- prolific_data %>%
  filter(status=="APPROVED")
demo_table <- psych::describe(prolific_data)
save(demo_table, file="Demographics.RData")
```

Descriptives Table
```{r}
descriptives_table <- psych::describe(gorilla_data)
save(descriptives_table, file="Descriptives.RData")

```